### ISSUE TITLE
pan_sharpen flag causing error in toolkit container

### ISSUE THREAD

**Issue by ssfinch** [nasa-nccs-hpda/evhr#34]
Apptainer> python /usr/local/ilab/evhr/view/evhrToaCLV.py --pan_sharpen -o output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes --scenes_in_file /explore/nobackup/projects/ilab/projects/vhr-toolkit/testing/evhr/toa_clv_test_alaska_cloud.csv
GDAL version: 3.4.3

Output directory: output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes
Band directory: output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes/1-bands
Strip directory: output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes/2-strips
DEM directory: output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes/3-dems
Ortho image directory: output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes/4-orthos
ToA directory: output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes/5-toas
No user-supplied DEM, defaulting to ADAPT SRTM/ASTERGDEM
In run
Number of input scenes 2
Set operation removed 0 scenes.
2 after removal of matching XMLs.
In _computeEnvelope
ogr2ogr -clipsrc -147.98909593 64.72323967 -147.48731072 64.96398015 -f "ESRI Shapefile" -select "Zone_Hemi" "/explore/nobackup/people/sstrong/.nccstmp/tmp7b1hctn9" "/usr/local/ilab/evhr/model/UTM_Zone_Boundaries/UTM_Zone_Boundaries.shp"
Return code: None
Message: b''
.
.
gdal_calc.py --calc="-10000*(A<-10000)+10000*(A>10000) + A*((A>=-10000)*(A<=10000))" --outfile=output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes/5-toas/WV02_20120809_M1BS_103001001A596600_BAND_N2.r100-ortho-toa.tif -A output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes/5-toas/WV02_20120809_M1BS_103001001A596600_BAND_N2.r100-ortho-toa-unbinned.tif --NoDataValue=-10001 --type=Int16
Return code: None
Message: b''
Merging bands into output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes/5-toas/WV02_20120809_M1BS_103001001A596600-toa.tif
Translating output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes/5-toas/WV02_20120809_M1BS_103001001A596600-toa-noncog.tif to COG output.toa.clv.vhr-toolkit-1.0.5-9-24-roger-scenes/5-toas/WV02_20120809_M1BS_103001001A596600-toa.tif
In _runPanSharpening
Creating pan. ToA for sharpening
Traceback (most recent call last):
File "/usr/local/ilab/evhr/view/evhrToaCLV.py", line 122, in <module>
sys.exit(main())
File "/usr/local/ilab/evhr/view/evhrToaCLV.py", line 115, in main
toa.run(dgScenes)
File "/usr/local/ilab/evhr/model/EvhrToA.py", line 665, in run
self.processStrips(stripsWithDgScenes,
File "/usr/local/ilab/evhr/model/EvhrToA.py", line 546, in processStrips
EvhrToA._runOneStrip(key,
File "/usr/local/ilab/evhr/model/EvhrToA.py", line 723, in _runOneStrip
EvhrToA._runPanSharpening(toaName, stripID, scenes, bandDir,
File "/usr/local/ilab/evhr/model/EvhrToA.py", line 791, in _runPanSharpening
panSharpeningToA = EvhrToA._runOneStrip(stripID,
TypeError: _runOneStrip() missing 1 required positional argument: 'logger'
Apptainer>

**Comment by ssfinch** [comment]
Roger did a hot fix and it has been tested.
